dist: trusty
sudo: false
env:
  global:
  - secure: E9NqrVqnpL/CyLSQBJsT2MmO54E2C9JwcU09fB32UlSou1XaUK32KGLVa/eEjN56mi6IskqScngc7FhiyVWnL0uGb/muVXuTczRV1Uz8nkgkU+DiEs2XjQd7QHnxgpYHcuE4ZPYW7aEacjsZvUQESW9MReCfCa2yj4WhqJZ9qf7p9+tmWM3VU9eyAIfUwPmE4BfkFEzNnqWerfzsqUgmecvhupgUh9gJRQ7HYG/6FCt+noW5u+9khjnHEWglFJFpC2tZa9PvwI+0MXbbXAanMzcLSVaJj/5hf9ol8ZqWrbomARy6JugSrnVl+C/xuAxl9gcoHhEHfVZDPxRrLS3l01iEaDNqEymx887KclKmtIhKqyyfDbGPK7JhQbMQQ/E7S8jAKe511rCFiUBWgI42MrJsfjAKsCR9GgbhPtU03uJd3kjB4ECb260KNM4QcsUPsTYAR7QApobrfvF6NgwIRHzF7z6iNvjTpJlESCpvBHogWTjZgOWysk22LLP34mLr996C0m1BjBUG7GbIhRIAyQ5b80aoUm/kpyXkdZYQfVzvzTDTr8ueouISOpPWnOm2ny3NypdVLnDxFMT/jxesZJmjYmt9BeOEnYxzHJJHwJJP+hj+JNkY/pgs+FiNH5aAA9ufP/nWsa8k8AEUjvsSrqXSHslWtFKX5ellgyoTOTU=
  - secure: hV1hZPQCEq3Wg5v2U6LPuuisrjqQbS1FlmZp49YsIOXmV1PSs8jpxUVqqmJoV3WbeuFKBNpn7YVXmHtbVMNMdroxLnd0YqlcIn2fXwzOSLCyw+eLq3+VjGS3EA7ETkrPoygGYOsBjqT+q2ZKQ9G+NNpdpcXX05jjhvzMN6t22DYMPB124AmSVJ4kmt7OxKYPhbm2k0LgVQr/YFuIvEjThG7Gf7OfXg1iXR7Iy2nv0Imxr0mpXXBHX4qSUfe5jQ7cTLzR3+wwKwL5rqfcdyLPl3sc4n9WnJrqToc7Q6qLSQMuDRc/1dxBziGFdilcWjoPjUqM+N3OrZey6Isc1pyA53bjogvLBhm5VPauSqLI4Il4GEeex67mM262MMXa4xobKCbSfcHu2VWMj+9xQXo5DOwmzWFryWeVhgOoEY5ENykD7HNfA1/jQNhNxXVtv+ojppf4OoeRe2MhGATgs7LN4UxjFs4eI8Te+qm+yEA9nU5sA69giMu//z9PCHmp5ybG5O8vWW+00QQjedyeWF9LIb1az2CavA6YHlhVwPpH4IQK18Sac0CTXUOSfnUaMW/rxKHuLuLW2kKl+oOc4rLhcAjvTdauje7CpRXERGSFJBb3ihT4nU+BRNVcecYbT5WxsOvVJgL1KlQsDiTBWAI8pvnCaDyAWSZCyvuP04uoLs0=
addons:
  sauce_connect: true
before_script:
  - cd src/test/test-app
  - npm install
  - npm run lite &
script:
  - jdk_switcher use oraclejdk8
  - cd ../../..
  - mvn test
  - cd src/test/test-app
  - npm run e2e
after_success:
  - bash <(curl -s https://codecov.io/bash)
